#!/usr/bin/env bash
#
# Loom one-command setup.
#
#   bash setup.sh
#
# Creates an isolated environment, installs Loom, asks for your database URL
# and (optional) API keys right here in the terminal, writes .env, and verifies
# the connection. Safe to run again any time.

set -euo pipefail

# ---- pretty output -----------------------------------------------------------
BOLD="$(printf '\033[1m')"; DIM="$(printf '\033[2m')"; RESET="$(printf '\033[0m')"
GREEN="$(printf '\033[32m')"; RED="$(printf '\033[31m')"; YELLOW="$(printf '\033[33m')"; CYAN="$(printf '\033[36m')"
say()  { printf "%s\n" "$*"; }
ok()   { printf "${GREEN}✓ %s${RESET}\n" "$*"; }
warn() { printf "${YELLOW}! %s${RESET}\n" "$*"; }
err()  { printf "${RED}✗ %s${RESET}\n" "$*" >&2; }
step() { printf "\n${BOLD}${CYAN}==> %s${RESET}\n" "$*"; }

cd "$(dirname "$0")"
PROJECT_DIR="$(pwd)"

printf "\n${BOLD}Loom setup${RESET}  ${DIM}(%s)${RESET}\n" "$PROJECT_DIR"

# ---- 1. Python ---------------------------------------------------------------
step "Checking Python"
PY=""
for c in python3.13 python3.12 python3.11 python3 python; do
  if command -v "$c" >/dev/null 2>&1; then
    if "$c" -c 'import sys; raise SystemExit(0 if sys.version_info[:2] >= (3,11) else 1)' 2>/dev/null; then
      PY="$c"; break
    fi
  fi
done
if [ -z "$PY" ]; then
  err "Python 3.11+ is required but was not found."
  say "Install it from https://www.python.org/downloads/ and run this again."
  exit 1
fi
ok "Using $($PY --version 2>&1) ($(command -v "$PY"))"

# ---- 2. Virtual environment + install ---------------------------------------
step "Creating isolated environment and installing Loom"
if [ ! -d .venv ]; then
  "$PY" -m venv .venv
  ok "Created .venv"
else
  ok ".venv already exists"
fi

# Use the venv's python directly. This avoids any other 'loom' on your PATH.
VPY="$PROJECT_DIR/.venv/bin/python"
[ -x "$VPY" ] || VPY="$PROJECT_DIR/.venv/Scripts/python.exe"  # Windows fallback

"$VPY" -m pip install --upgrade pip >/dev/null
say "${DIM}Installing dependencies (this can take a minute)...${RESET}"
"$VPY" -m pip install -e ".[dev]" >/dev/null
ok "Loom installed in .venv"

# ---- 3. Collect configuration -----------------------------------------------
step "Configuration"

reuse_env="no"
if [ -f .env ]; then
  printf "A .env file already exists. Reuse it without changes? [Y/n] "
  read -r ans || true
  case "${ans:-Y}" in
    [Nn]*) reuse_env="no" ;;
    *)     reuse_env="yes" ;;
  esac
fi

if [ "$reuse_env" = "yes" ]; then
  ok "Keeping existing .env"
else
  say "Enter everything Loom needs. ${DIM}Required is marked; press Enter to skip optional ones.${RESET}"
  say ""

  # --- Database (required) ---
  say "${BOLD}1) Database${RESET}  ${DIM}(required)${RESET}"
  say "${DIM}   Supabase: Project Settings → Database → Connection string → URI${RESET}"
  say "${DIM}   postgresql://postgres:PASSWORD@db.REF.supabase.co:5432/postgres${RESET}"
  DB_URL=""
  while [ -z "$DB_URL" ]; do
    printf "   ${BOLD}Database URL:${RESET} "
    read -r DB_URL || true
    [ -z "$DB_URL" ] && warn "   Required — please paste the connection string."
  done

  # --- Gemini key (optional: smart search + AI answers) ---
  say ""
  say "${BOLD}2) Gemini API key${RESET}  ${DIM}(optional — enables smart semantic search + /ask answers)${RESET}"
  say "${DIM}   Get one free at https://aistudio.google.com/apikey${RESET}"
  printf "   ${BOLD}Gemini API key:${RESET} "
  read -r GEMINI_KEY || true

  # --- Slack (optional) ---
  say ""
  say "${BOLD}3) Slack${RESET}  ${DIM}(optional — let Loom learn from team chat; press Enter to skip)${RESET}"
  say "${DIM}   Bot token starts with xoxb-  ,  App token starts with xapp-${RESET}"
  printf "   ${BOLD}Slack bot token (xoxb-…):${RESET} "
  read -r SLACK_BOT || true
  SLACK_APP=""
  if [ -n "${SLACK_BOT:-}" ]; then
    printf "   ${BOLD}Slack app token (xapp-…):${RESET} "
    read -r SLACK_APP || true
  fi

  # --- Derive providers from what was given ---
  if [ -n "${GEMINI_KEY:-}" ]; then
    LLM_PROVIDER="gemini"; EMB_PROVIDER="gemini"
  else
    LLM_PROVIDER="skip";   EMB_PROVIDER="none"
  fi

  # --- Auto-generate API tokens (needed when Slack is enabled; harmless otherwise) ---
  gen_token() { "$VPY" -c "import secrets;print(secrets.token_urlsafe(32))"; }
  API_KEY="$(gen_token)"
  INTERNAL_TOKEN="$(gen_token)"

  umask 077   # .env may contain secrets -> keep it private
  {
    echo "# Generated by setup.sh"
    echo "LOOM_ENV=development"
    echo "LOOM_DATABASE_URL=$DB_URL"
    echo ""
    echo "LOOM_API_KEY=$API_KEY"
    echo "LOOM_INTERNAL_API_TOKEN=$INTERNAL_TOKEN"
    echo "LOOM_API_BASE_URL=http://localhost:8000"
    echo "LOOM_API_HOST=127.0.0.1"
    echo "LOOM_API_PORT=8000"
    echo ""
    echo "LOOM_LLM_PROVIDER=$LLM_PROVIDER"
    echo "GEMINI_API_KEY=${GEMINI_KEY:-}"
    echo ""
    echo "LOOM_EMBEDDING_PROVIDER=$EMB_PROVIDER"
    echo "LOOM_EMBEDDING_MODEL=gemini/text-embedding-004"
    echo ""
    echo "LOOM_SLACK_BOT_TOKEN=${SLACK_BOT:-}"
    echo "LOOM_SLACK_APP_TOKEN=${SLACK_APP:-}"
    echo "LOOM_SLACK_SILENT=true"
    echo "LOOM_LOG_LEVEL=INFO"
  } > .env
  ok "Wrote .env"
  if [ "$EMB_PROVIDER" = "none" ]; then
    warn "No Gemini key — Loom will use plain text search (add a key to .env later for smart search)."
  fi
fi

# ---- 4. Verify the database connection --------------------------------------
step "Connecting to your database"
if "$VPY" -m loom status; then
  :
fi

# Strict check so a bad URL fails loudly (loom status never crashes by design).
# Errors are summarized cleanly below instead of dumping a Python traceback.
if ! "$VPY" - >/dev/null 2>/tmp/loom_setup_dbcheck.err <<'PY'
import asyncio
from loom.config import LoomConfig
from loom.db import DatabasePool
async def main():
    cfg = LoomConfig.from_env()
    pool = DatabasePool(cfg, mode="async")
    await pool.init_async()
    await pool.close_async()
asyncio.run(main())
PY
then
  err "Could not connect to the database."
  say ""
  say "Most likely the connection string is wrong. Check ${BOLD}LOOM_DATABASE_URL${RESET} in .env:"
  say "  • password is correct (no leftover [ ] brackets)"
  say "  • project ref / host has no typos"
  say "  • for Supabase, use the URI from Settings → Database → Connection string"
  say ""
  say "Then run this again:  ${CYAN}bash setup.sh${RESET}"
  exit 1
fi
ok "Database connected and tables ready"

# ---- 5. Generate the ready-to-paste MCP config ------------------------------
step "Your MCP config (copy this into your coding tool)"

# Built from your actual .env, with the venv's absolute python so it always
# resolves to THIS Loom regardless of PATH or which folder the tool launches in.
MCP_FILE="$PROJECT_DIR/loom-mcp.json"
"$VPY" - "$VPY" > "$MCP_FILE" <<'PY'
import json, sys
from loom.config import LoomConfig

vpy = sys.argv[1]
cfg = LoomConfig.from_env()

env = {"LOOM_DATABASE_URL": cfg.database_url}
if cfg.embedding_provider == "gemini" and cfg.embedding_api_key:
    env["GEMINI_API_KEY"] = cfg.embedding_api_key
    env["LOOM_EMBEDDING_PROVIDER"] = "gemini"
    env["LOOM_EMBEDDING_MODEL"] = cfg.embedding_model
else:
    env["LOOM_EMBEDDING_PROVIDER"] = "none"

payload = {
    "mcpServers": {
        "loom": {
            "command": vpy,
            "args": ["-m", "loom.mcp.server"],
            "env": env,
        }
    }
}
print(json.dumps(payload, indent=2))
PY

ok "Saved to ${MCP_FILE}"
say ""
say "${DIM}---------------------------------------------------------------------${RESET}"
cat "$MCP_FILE"
say "${DIM}---------------------------------------------------------------------${RESET}"

# ---- 6. Done -----------------------------------------------------------------
step "All set!"
cat <<EOF

${BOLD}Final step — paste the JSON above into your coding tool, then restart it:${RESET}

  ${BOLD}Cursor${RESET}        → create a file ${CYAN}.cursor/mcp.json${RESET} in your project (or edit the global one)
  ${BOLD}Claude Code${RESET}   → run:  ${CYAN}claude mcp add-json loom '$(cat "$MCP_FILE" | tr -d '\n')'${RESET}
  ${BOLD}Claude Desktop${RESET}→ add the same block to your claude_desktop_config.json

That's it. Your coding agent can now call Loom's tools (session_init, recall,
teach, get_stats). The config above is also saved at:
  ${CYAN}${MCP_FILE}${RESET}

${DIM}Optional — run Loom yourself from the terminal (no PATH issues):${RESET}
  ${DIM}.venv/bin/loom serve${RESET}      ${DIM}# start the HTTP API${RESET}
  ${DIM}.venv/bin/loom status${RESET}     ${DIM}# health check${RESET}

EOF
ok "Done"
