"""Centralized default constants for Loom.

Values here are defaults that are not user-tunable per-deployment. Anything a
deployment may want to override lives on ``LoomConfig`` instead.
"""

APP_NAME = "loom"
APP_VERSION = "1.0.0"

DEFAULT_API_HOST = "0.0.0.0"  # noqa: S104 - intended default for containers
DEFAULT_API_PORT = 8000
DEFAULT_LOG_LEVEL = "INFO"

DB_MIN_SIZE = 2
DB_MAX_SIZE = 10
DB_COMMAND_TIMEOUT_SECONDS = 30
DB_MAX_INACTIVE_CONNECTION_LIFETIME_SECONDS = 300
DB_SLOW_QUERY_MS = 500

DB_SYNC_MIN_SIZE = 1
DB_SYNC_MAX_SIZE = 5

EMBEDDING_MODEL = "gemini/text-embedding-004"
EMBEDDING_DIMENSION = 768
EMBEDDING_INPUT_MAX_CHARS = 3000
EMBEDDING_CACHE_SIZE = 256

DEFAULT_MAX_RULES_PER_SESSION = 10
DEFAULT_MAX_CONTEXTS_PER_SESSION = 3
DEFAULT_CONTEXT_MAX_CHARS = 500
DEFAULT_CONTEXT_TTL_DAYS = 30
DEFAULT_BLOB_TTL_DAYS = 14
DEFAULT_CONTEXT_HALF_LIFE_DAYS = 10.0

DEFAULT_GATEKEEPER_IDLE_SECONDS = 180
DEFAULT_GATEKEEPER_DEBOUNCE_SECONDS = 180
DEFAULT_SLACK_BUFFER_MAX_MESSAGES = 30
DEFAULT_SLACK_RECONNECT_BACKOFF_MAX_SECONDS = 60

DEFAULT_HTTP_TIMEOUT_SECONDS = 30
DEFAULT_LLM_TIMEOUT_SECONDS = 45
DEFAULT_LLM_TEMPERATURE = 0.2
DEFAULT_LLM_MAX_TOKENS = 1000

MEMORY_RULE_MAX_CHARS = 1000
MEMORY_RULE_MIN_CHARS = 5
MEMORY_EXAMPLE_MAX_CHARS = 500
MEMORY_DOMAIN_MAX_CHARS = 50
MEMORY_RULE_TYPE_MAX_CHARS = 50
SESSION_TASK_MAX_CHARS = 500
ASK_MESSAGE_MAX_CHARS = 10000

CONTEXT_SUMMARY_MIN_CHARS = 10

BLOB_MAX_MESSAGES = 100

EXPORT_SCHEMA_VERSION = "1.0.0"

# Max length we will accept for an inbound X-Request-ID header before truncation.
REQUEST_ID_MAX_CHARS = 64

# Health-check latency threshold (ms) above which status is "degraded".
HEALTH_DEGRADED_LATENCY_MS = 500.0
